### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-10119

Is there anything we should note about configuration here? e.g. what to do if the site is using gtm_barebones module instead of google_tag?

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
I've seen the instructions on https://github.com/UN-OCHA/gms-site/pull/412#issuecomment-1970602001 - I'll push an update before asking again for a review.

**Comment by lazysoundsystem** [comment]
A little confused - running `drush eval "ocha_monitoring_enforce_monitors();" && drush -y cex` included most of the non-ocha monitoring config that's in https://github.com/UN-OCHA/gms-site/pull/412/files - which also get included by `git add config/monitoring.se*` (from https://humanitarian.atlassian.net/browse/OPS-9765).

@attiks This now covers the config files included in https://github.com/UN-OCHA/gms-site/pull/414 - is this what we want?

**Comment by attiks** [comment]
My bad, it's fine to add all of them in config, the code just disables the ones we don't need

**Comment by lazysoundsystem** [comment]
Just to clarify - is it better to go back to the original suggestion 
```
Commit the monitoring-related config changes (including composer files and
`config/core.extension.yml`).
```
or is the current suggestion more concise:
```
Commit the following files:
`config/core.extension.yml`).
`composer.json`
`composer.lock`
`config/core.extension.yml`
`config/views.view.monitoring_sensor_results.yml`
`config/language/*/views.view.monitoring_sensor_results.yml`
`config/monitoring.settings.yml`
`config/monitoring.sensor_config.ocha_*`
```

**Comment by attiks** [comment]
We should add all files (`config/monitoring.sensor_config.*`) to be safe, the `monitor` module otherwise tries to create sensors, so config will be out of sync

**Comment by lazysoundsystem** [comment]
@attiks I think this is ready to merged now. (I'm waiting on it before creating tickets to add the module to FTS and HumanitarianAction.)

**Review by attiks — APPROVED** [review]
Thanks

**Pull request merged**
